---
title: "Untitled"
author: "u7151703"
date: "2024-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
result_sub = result_total %>% filter(classes > 9)


t.test(result_sub$nrf_main1, result_sub$nrf_main2, paired = TRUE)
```


```{r}
ggplot(result_total, aes(x= pythia_score, y = nrf, color = ntaxa))+
  scale_color_gradientn(
    values = seq(0,1),
    colors = c('#91c1d4', "#ddf1f3", "#ecf4dd", "#fff7ac", "#ecb477", "#E87651"),
    )+
  geom_point()+
  theme_bw()

ggplot(result_total%>% filter(classes > 5), aes(x= pythia_score, y = nrf_main1 - nrf_main2, color = ntaxa))+
  scale_color_gradientn(
    values = seq(0,1),
    colors = c('#91c1d4', "#ddf1f3", "#ecf4dd", "#fff7ac", "#ecb477", "#E87651"),
    )+
  geom_point()+
  theme_bw()


ggplot(result_total, aes(x= pythia_score, y = nrf_gene2, color = ntaxa))+
  scale_color_gradientn(
    values = seq(0,1),
    colors = c('#91c1d4', "#ddf1f3", "#ecf4dd", "#fff7ac", "#ecb477", "#E87651"),
    )+
  geom_point()+
  theme_bw()

```

```{r}
ggplot(result_total, aes(x= pythia_score, y  = ntaxa, color =log10(nsites)))+
  geom_point()+
  facet_wrap(~as.factor(classes))+
  theme_bw()

ggplot(result_total, aes(x= pythia_score, y  = nsites, color = ntaxa))+
  geom_point()+
  facet_wrap(~as.factor(classes))+
  theme_bw()

ggplot(result_total, aes(x= nsites, y  = ntaxa, color = pythia_score))+
  geom_point()+
  facet_wrap(~as.factor(classes))+
  scale_color_gradientn(
    values = seq(0,1),
    colors = c('#91c1d4', "#ddf1f3", "#ecf4dd", "#fff7ac", "#ecb477", "#E87651"),
    )+
  theme_bw()
```

```{r}
ggplot(result_total, aes(x= pythia_score, y = nrf, color = classes))+
  scale_color_gradientn(
    values = seq(0,1),
    colors = c('#91c1d4', "#ddf1f3", "#ecf4dd", "#fff7ac", "#ecb477", "#E87651"),
    )+
  geom_point()+
  theme_bw()

```

```{r}
ggplot(result_total, aes(x= pythia_score, y = nrf, ))+
  geom_point()+
  facet_wrap(~as.factor(classes))+
  theme_bw()


ggplot(result_total %>% filter(classes > 2), aes(x= pythia_score, y = nrf, color = classes))+
  scale_color_gradientn(
    values = seq(0,1),
    colors = c('#91c1d4', "#ddf1f3", "#ecf4dd", "#fff7ac", "#ecb477", "#E87651"),
    )+
  geom_point()+
  theme_bw()
```

```{r}
ggplot(result_total, aes(x= pythia_score))+
  geom_histogram()+
  facet_wrap(~as.factor(classes))+
  theme_bw()

ggplot(result_total, aes(x= ntaxa))+
  geom_density()+
  #facet_wrap(~as.factor(classes))+
  theme_bw()

ggplot(result_total, aes(x= nsites))+
  geom_density()+
  #xlim(0,500)+
  #facet_wrap(~as.factor(classes))+
  theme_bw()
```

```{r}
filter_num <- result_total$num[which(result_total$classes > 2)]
cat(filter_num, sep = ", ")
```


