---
title: "Untitled"
author: "u7151703"
date: "2024-09-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#ref
```{r}
main363_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/ref_trees/63K_abb.treefile")
exon363_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/ref_trees/exon_ref_unrooted.treefile")
```

```{r}
main363_tree <- root(main363_tree, outgroup = 'STRCAM', edgelabel = TRUE)
exon363_tree <- root(exon363_tree, outgroup = 'STRCAM', edgelabel = TRUE)
```


```{r}
mix12_1k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/mix12_1k_unrooted.treefile")
mix12_1k_tree <- root(mix12_1k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
sin12_1k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/sin12_1k_unrooted.treefile")
sin12_1k_tree <- root(sin12_1k_tree, outgroup = 'STRCAM', edgelabel = TRUE)

mix12_1k_f_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/mix12_1k_filter_unrooted.treefile")
mix12_1k_f_tree <- root(mix12_1k_f_tree, outgroup = 'STRCAM', edgelabel = TRUE)
sin12_1k_f_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/sin12_1k_filter_unrooted.treefile")
sin12_1k_f_tree <- root(sin12_1k_f_tree, outgroup = 'STRCAM', edgelabel = TRUE)

mix12_1k_f1c_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/mix12_1k_f1c_unrooted.treefile")
mix12_1k_f1c_tree <- root(mix12_1k_f1c_tree, outgroup = 'STRCAM', edgelabel = TRUE)
sin12_1k_f1c_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/sin12_1k_f1c_unrooted.treefile")
sin12_1k_f1c_tree <- root(sin12_1k_f1c_tree, outgroup = 'STRCAM', edgelabel = TRUE)

mix12_1k_f2c_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/mix12_1k_f2c_unrooted.treefile")
mix12_1k_f2c_tree <- root(mix12_1k_f2c_tree, outgroup = 'STRCAM', edgelabel = TRUE)
sin12_1k_f2c_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/sin12_1k_f2c_unrooted.treefile")
sin12_1k_f2c_tree <- root(sin12_1k_f2c_tree, outgroup = 'STRCAM', edgelabel = TRUE)

mix12_2k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/mix12_2k_unrooted.treefile")
mix12_2k_tree <- root(mix12_2k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
sin12_2k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/sin12_2k_unrooted.treefile")
sin12_2k_tree <- root(sin12_2k_tree, outgroup = 'STRCAM', edgelabel = TRUE)

mix12_2k_f75p_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/mix12_2k_f75p_unrooted.treefile")
mix12_2k_f75p_tree <- root(mix12_2k_f75p_tree, outgroup = 'STRCAM', edgelabel = TRUE)
sin12_2k_f75p_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/sin12_2k_f75p_unrooted.treefile")
sin12_2k_f75p_tree <- root(sin12_2k_f75p_tree, outgroup = 'STRCAM', edgelabel = TRUE)

mix12_2k_f2c_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/mix12_2k_f2c_unrooted.treefile")
mix12_2k_f2c_tree <- root(mix12_2k_f2c_tree, outgroup = 'STRCAM', edgelabel = TRUE)
sin12_2k_f2c_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/sin12_2k_f2c_unrooted.treefile")
sin12_2k_f2c_tree <- root(sin12_2k_f2c_tree, outgroup = 'STRCAM', edgelabel = TRUE)
```



```{r}
tree1 <- groupOTU(main363_tree, grp, 'clade')
tree2 <- groupOTU(sin12_2k_f2c_tree, grp, 'clade')

p1 <- ggtree(tree1, branch.length = 'none', aes(color = clade))
p2 <- ggtree(tree2, branch.length = 'none', aes(color = clade))

p1$data$clade <- factor(p1$data$clade, levels = c('Palaeognathae_1','Galloanseres_2','Mirandornithes_3',
                                            'Columbimorphae_4','Otidimorphae_5','Opisthocomiformes_6',
                                            'Cursorimorphae_7','Strisores_8','Phaethontimorphae_9',
                                            'Aequornithes_10','Afroaves_11','Australaves_12'))
d1 <- p1$data





p2$data$clade <- factor(p2$data$clade, levels = c('Palaeognathae_1','Galloanseres_2','Mirandornithes_3',
                                            'Columbimorphae_4','Otidimorphae_5','Opisthocomiformes_6',
                                            'Cursorimorphae_7','Strisores_8','Phaethontimorphae_9',
                                            'Aequornithes_10','Afroaves_11','Australaves_12'))
d2 <- p2$data

d2$x <- max(d2$x) - d2$x + max(d1$x) + 15 #4
dd = bind_rows(d1,d2) %>% 
  filter(!is.na(label)) 

p1 <- p1 +
  geom_tree()+
  geom_tree(data = d2)+
  geom_tiplab(size = 1.5)+
  geom_tiplab(data= d2, size = 1.5, hjust=1)+
  geom_nodelab(size = 1.5, nudge_x = -0.7, nudge_y = 0.6)+
  geom_nodelab(data=d2, size = 1.5, nudge_x = 0.7, nudge_y = 0.6 )+
  geom_line(aes(x, y, group=label), data=dd %>% filter(isTip), alpha=0.3)
```


```{r}
output_path <- "C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/full/mix12_2k_f2c_vs_main.pdf"

pdf(file = output_path, width = 20, height = 20)
print(p1)
dev.off()

```

# filter 2
```{r}
main_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/ref_trees/main_filter2.treefile")
exon_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/ref_trees/exon_filter2.treefile")

main_tree <- root(main_tree, outgroup = 'STRCAM', edgelabel = TRUE)
exon_tree <- root(exon_tree, outgroup = 'STRCAM', edgelabel = TRUE)
```


```{r}
mixc123_3k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/filter2/exon1k/mix123_3k_unrooted.treefile")
mixc123_3k_tree <- root(mixc123_3k_tree, outgroup = 'STRCAM', edgelabel = TRUE)

mixc123_9k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/filter2/exon1k/mix123_0_9k_unrooted.treefile")
mixc123_9k_tree <- root(mixc123_9k_tree, outgroup = 'STRCAM', edgelabel = TRUE)

mixc12_3k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/filter2/exon1k/mix12_3k_unrooted.treefile")
mixc12_3k_tree <- root(mixc12_3k_tree, outgroup = 'STRCAM', edgelabel = TRUE)

mixc12_6k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/filter2/exon1k/mix12_6k_unrooted.treefile")
mixc12_6k_tree <- root(mixc12_6k_tree, outgroup = 'STRCAM', edgelabel = TRUE)

mixc12_14k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/filter2/exon1k/mix12_14k_unrooted.treefile")
mixc12_14k_tree <- root(mixc12_14k_tree, outgroup = 'STRCAM', edgelabel = TRUE)

c1c12_3k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/filter2/exon1k/c112_3k_unrooted.treefile")
c1c12_3k_tree <- root(c1c12_3k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
```

# filter 3
# 1000 loci
```{r}
partc12_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon1k/part12_1k_unrooted.treefile")
partc123_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon1k/part123_1k_unrooted.treefile")
mixc12_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon1k/mix12_1k_unrooted.treefile")
mixc123_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon1k/mix123_1k_unrooted.treefile")
ref_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon1k/ref_1k_pruned_unrooted.treefile")
```

```{r}
partc12_tree <- root(partc12_tree, outgroup = 'STRCAM', edgelabel = TRUE)
partc123_tree <- root(partc123_tree, outgroup = 'STRCAM', edgelabel = TRUE)
mixc12_tree <- root(mixc12_tree, outgroup = 'STRCAM', edgelabel = TRUE)
mixc123_tree <- root(mixc123_tree, outgroup = 'STRCAM', edgelabel = TRUE)
ref_tree <- root(ref_tree, outgroup = 'STRCAM', edgelabel = TRUE)
```

```{r}
partc12_2k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon2k/part12_2k_unrooted.treefile")
partc123_2k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon2k/part123_2k_unrooted.treefile")
mixc12_2k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon2k/mix12_2k_unrooted.treefile")
mixc123_2k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon2k/mix123_2k_unrooted.treefile")
ref_2k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon2k/ref_2k_pruned_unrooted.treefile")
c1123_2k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon2k/c1123_2k_unrooted.treefile")
c112_2k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon2k/c112_2k_unrooted.treefile")

partc12_2k_tree <- root(partc12_2k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
partc123_2k_tree <- root(partc123_2k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
mixc12_2k_tree <- root(mixc12_2k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
mixc123_2k_tree <- root(mixc123_2k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
ref_2k_tree <- root(ref_2k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
c1123_2k_tree <- root(c1123_2k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
c112_2k_tree <- root(c112_2k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
```


```{r}
mixc123_7k_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon7k/mix123_7k_unrooted.treefile")

mixc123_7k_tree <- root(mixc123_7k_tree, outgroup = 'STRCAM', edgelabel = TRUE)
```

```{r}
mixc123_all_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/exon_all/mix123_all_unrooted.treefile")

mixc123_all_tree <- root(mixc123_all_tree, outgroup = 'STRCAM', edgelabel = TRUE)
```

# intergenic
```{r}
mix_chr1_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/inter/mix_chr1_unrooted.treefile")
c1_chr1_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/inter/c1_chr1_unrooted.treefile")
ref_chr1_tree <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/draft_results/inter/ref_chr1_unrooted.treefile")

mix_chr1_tree <- root(mix_chr1_tree, outgroup = 'STRCAM', edgelabel = TRUE)
c1_chr1_tree <- root(c1_chr1_tree, outgroup = 'STRCAM', edgelabel = TRUE)
ref_chr1_tree <- root(ref_chr1_tree, outgroup = 'STRCAM', edgelabel = TRUE)
```

# DRAFT
```{r}
treea <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/0_GALGAL_R17801_uniqueexon.treefile")
treeb <- ape::read.tree("C:/Users/u7151703/OneDrive - Australian National University/Desktop/research/aves_evo/0_GALGAL_R17801_unique.treefile")

treea <- root(treea, outgroup = 'COTJAP', edgelabel = TRUE)
treeb <- root(treeb, outgroup = 'COTJAP', edgelabel = TRUE)
```




