
import os


# filter 2
result_string = 'CALSQU COLVIR ODOGUJ GALGAL COTJAP PHACOL MELGAL NUMMEL PENPIL ANSSEM ANSCYG CAIMOS ASASCU ANAPLA MELVER PROCAF DICEXI CHLCYA CHLHAR IRECYA PEUTAE PRUFUL PRUHIM PASDOM HYPCIN MOTALB CHLVIR HEMWIL SERCAN LOXCUR LOXLEU RHOROS CALORN EMBFUC PHEMEL CARCAR PASAMO NESACU GEOFOR SPOHYP SPIPAS MELMEL JUNHYE ZONALB SETCOR SETKIR AGEPHO MOLATE UROPYL PLONIG VIDCHA VIDMAC LONSTR TAEGUT PHANIT REGSAT SITEUR POLCAE THRLUD CERBRA ELAFOR BUPERY TOXRED RHAINO LEUROT CINMEX CATFUS CERCOR COPSEC ERIRUB FICALB SAXMAU ANTMIN POEATR PARMAJ ALACHE PANBIA NICCHL SYLVIR CISJUN ACRARU HIPICT LOCOCH OXYMAD DONATR HIRRUS PHYTRO RHASIB HYLPRA AEGCAU ERYMCC CETCET HORVUL BRAATR PYCJOC SINWEB SYLATR SYLBOR STEDEN ZOSHYP PORRUF ILLCLE LEILUT DRYBRU CHAFRE PICGYM CALWIL NOTCIN PTILEU EDOCOE CHAPAP RHIDAH DICMEG MYIHEB STRCIN IFRKOW PARRAG LANLUD APHCOE CORMON CORBRA MOHOCH MACNIG GYMTIB RHALEU DRYGAM DYACAS MYSCRO DAPCHR EULNIG ALERUF FALFRO PACPHI ORIORI OREARF PTEMEL ERPZAN ORTSPA POSRUF MALELE DASBRO GRAPIC ORISOL PARPUN CLIRUF PTIVIO MENNOV SERLUN SAPAEN PITSOR CALVIR RHEHOF GRAVAR SCYSUP FORRUF SCLMEX FURFIG CAMPRO LEPCOR CEPORN PACMIN ONYCOR OXYCRI PIPCHL NEOCIN TACRUB MIOMAC NESNOT EOLROS AMAGUI AGAROS FALPER BUCABY RHICYA MERNUB EURGUL TODMEX BARMAR CEYCYA CHLAEN GALDEA PICPUB INDMAC PSIHAE TRILEU EUBBOU RAMSUL GLABRA CICNIG SAGSER PANHAL CIRPEC HALLEU AQUCHR SPITYR THACHL FREGRA HYDTET FULGLA PELURI CICMAG MESCAY NIPNIP COCCOC EGRGAR BALREX SCOUMB FREMAG SULDAC ANHANH ANHRUF PHACAR URIPEL NANHAR NANAUR NYCLEU ANTCAR STECAR NYCBRA NYCGRA PODSTR AEGBEN CHAPEL HEMCOM CALANN BURBIS CHIMIN CHAALE CHAVOC HIMHIM IBISTR LIMLAP AREINT CALPUG PEDTOR THIORB JACJAC NYCSEM ROSBEN TURVEL DROARD GLAPRA RHIAFR STEPAR CEPGRY ALCTOR URIAAL PHASIM RYNNIG RISTRI CHRMAC LARSMI HELFUL ZAPATR PSOCRE ARAGUA BALREG SYRPAR CALNIC COLPIC COLLIV CORCRI ARDKOR CROSUL CENBEN CENUNI CUCCAN PIACAY APTOWE APTROW EUDELE NOTPER NOTORN NOTJUL NOTNIG TINGUT CRYSOU CRYCIN'

with open("exon_namelist_random.txt") as f:
    f_list = f.readlines()

for i in range(0,100):
    if not os.path.exists('c12_concat'):
        os.makedirs('c12_concat')

    name = f_list[i].split(" ")[1].rstrip()    
    f_name = 'c12/'+ name + '.cds.fa'
    filtered_f_name = 'c12_concat/'+ name + '.cds.fa-out.fas'
    if not os.path.isfile(filtered_f_name):
        filter_cmd = 'python3 AMAS.py remove -x ' + result_string + ' -d dna -f fasta -i ' + f_name + ' -u fasta -g c12_concat/'
        os.system(filter_cmd)

concat_cmd = 'python3 AMAS.py concat -d dna -f fasta -i c12_concat/GAL* --part-format nexus -u fasta -n 12 -p c12_concat/c12_100_partitions.txt -t c12_concat/c12_100_concat.fas'
os.system(concat_cmd)

